echo " the currently logged in user is $USER "
echo " the current shell is $SHELL "
echo " the home drectory is $HOME "
echo " the os type is $OSTYPE "
echo " the current path setting is $PATH "
echo " the working directory is $PWD "
echo " there are $(who | wc -l) users logged in "
